version: "3"
services:
  nginx:
    depends_on:
      - kb-oms-client
    restart: always
    image: "nginx:latest"
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
  kb-oms-client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /app/node_modules
      - ./:/app
