version: "3"
services:
  nginx:
    depends_on:
      - kb-oms
    restart: always
    image: "nginx:latest"
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./kb-oms
    volumes:
      - /app/node_modules
      - ./kb-oms:/app
